"use client";
import "./globals.css";
import { SessionProvider, useSession } from "next-auth/react";

// export const metadata = {
//   title: "feedback app",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProvider>
        <body>{children}</body>
      </SessionProvider>
    </html>
  );
}
