"use client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import "./globals.css";
import { SessionProvider, useSession } from "next-auth/react";
// export const metadata = {
//   title: "feedback app",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const queryClient = new QueryClient()

  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <SessionProvider>
          <body>{children}</body>
        </SessionProvider>
      </QueryClientProvider>
    </html>
  );
}
